spring:
  datasource:
    url: jdbc:mysql://rm-2vc088510r843d0sfeo.mysql.cn-chengdu.rds.aliyuncs.com:3306/ebidding_bid?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: cqteam
#    password: root
 #   password: lyy020314
    password: cq-team00

  jpa:
    show-sql: true

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848