spring:
  datasource:
    url: jdbc:mysql://rm-2vc088510r843d0sfeo.mysql.cn-chengdu.rds.aliyuncs.com:3306/ebidding_account?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: cqteam
    password: cq-team00
 #   password: lyy020314
#  password: root


  jpa:
    show-sql: true