spring:
  cloud:
    gateway:
      routes:
        - id: account_service
          uri: http://localhost:8001
          predicates:
            - Path=/api/v1/account-service/**
          filters:
            JwtFilter
        - id: bid_service
          uri: http://localhost:8002
          predicates:
            - Path=/api/v1/bid-service/**
          filters:
            JwtFilter
        - id : bwic_service
          uri: http://localhost:8003
          predicates:
            - Path=/api/v1/bwic-service/**
          filters:
            JwtFilter