apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
      env: test
  template:
    metadata:
      labels:
        app: ui
        env: test
    spec:
      containers:
        - name: ui
          image: ebidding/ui
          imagePullPolicy: Never
          ports:
            - name: http-port
              containerPort: 80
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 600Mi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: common-config
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui
    env: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80