spring:
  datasource:
    url: jdbc:mysql://rm-2vc088510r843d0sfeo.mysql.cn-chengdu.rds.aliyuncs.com:3306/ebidding_bwic?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: cqteam
    password: cq-team00
#   password: root
#    password: lyy020314

    cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848

  jpa:
    show-sql: true

ebidding:
  account-endpoint: localhost:8001
  bid-endpoint: localhost:8002
  bwic-endpoint: localhost:8003