spring:
  datasource:
    url: jdbc:h2:file:./test/ebidding_accounts
    username: root
    password: 123456
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none
    show-sql: true